twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        logo_service: '@App\Service\LogoService'
        navbar_service: '@App\Service\NavbarService'

when@test:
    twig:
        strict_variables: true
